// Copies the approved ring geometry out of the design asset into a TS module.
import { readFileSync, writeFileSync } from 'node:fs';

const svg = readFileSync('docs/superpowers/specs/assets/photo-mark.svg', 'utf8');
const find = (id: string) => {
  const m = new RegExp(`<path d="(M[^"]+)" fill="url\\(#${id}\\)"`).exec(svg);
  if (!m) throw new Error(`Path for #${id} not found`);
  return m[1];
};
const out = `// Generated by scripts/extract-brush-paths.ts from docs/superpowers/specs/assets/photo-mark.svg. Do not edit.
export const RING_MAIN = ${JSON.stringify(find('ink2'))};
export const RING_SECOND = ${JSON.stringify(find('ink22'))};
`;
writeFileSync('src/lib/brush-ring.ts', out);
console.log('src/lib/brush-ring.ts written.');
